Add unit cell extraction when not provided

diff --git a/analyzer b/analyzer
--- a/analyzer
+++ b/analyzer
@@ -35,7 +35,8 @@ Workflow parameters:
 	-i, --input
 		Input file name (name or mask)
 	-o, --output
-		Output HKL file name template
+		Output HKL file name template.
+		Default: 'oanalyzer_YYYY-MM-DD-HH-SS'
 	--cell, -p
 		Unit cell file (used for compare_hkl only)
 	--merging
@@ -85,12 +86,13 @@ CLEANUP=1
 ############################
 # READING INPUT PARAMETERS #
 ############################
-while [[ $# -gt 1 ]]; do
+while [[ $# -gt 0 ]]; do
 	key="$1"
 	echo "..Current argument is ${key}"
 	case "$key" in 
 		-h|--help)
-			echo "${HELP_STRING}"; exit 0
+			echo "${HELP_STRING}";
+			exit 0
 	shift
 	;;
 	#----------------------------------------
@@ -129,12 +131,12 @@ while [[ $# -gt 1 ]]; do
 	shift # past argument or value
 done
 
+
 ################################################
 # CHECKING THAT ALL INPUT PARAMETERS ARE VALID #
 ################################################
 
-
-if ! (touch "$OUTPUT"); then
+if ! (touch "$OUTPUT" &> /dev/null); then
 	echo "Could not access output ${OUTPUT}"
 	echo "Please check access right and/or folder structure"
 	exit 1
@@ -142,14 +144,20 @@ else
 	rm "$OUTPUT"
 fi
 
-if ! (touch "$CELL"); then
-	echo "Could not access cell ${CELL}"
-	echo "Will continue with cell from the stream"
-	echo "Please check access right and/or folder structure"
-	exit 1
+if ! (touch "$CELL" &> /dev/null); then
+	echo "Could not access cell <${CELL}> (or you did not provide it), please check access right and/or folder structure"
+	echo "Will proceed using cell from the stream"
+	python3 extract_cell.py ${INPUT} > tmp."$OUTPUT".cell
 else
 	rm "$OUTPUT"
 fi
+
+cat tmp."$OUTPUT".cell
+
+#################
+# RATE FUNCTION #
+#################
+
 
 
 ###########
@@ -157,6 +165,6 @@ fi
 ###########
 if [ "$CLEANUP" ]; then 
 	echo "......."
-	echo 'Removing according to tmp.* mask'
-	rm tmp.* &
+	echo "Removing according to tmp.${OUTPUT} mask"
+	rm tmp.${OUTPUT}* &
 fi
