Add multiple yaml file reading and tail -f mode for slurm

diff --git a/runner b/runner
--- a/runner
+++ b/runner
@@ -67,8 +67,11 @@ create_variables() {
 
 
 time=$(date "+%Y_%m_%d_%H_%M_%S")
-if ! create_variables "$1"; then
-	echo "Please provide input yaml file"; exit 1; fi
+for var in "$@"; do
+	if ! create_variables "$var"; then
+		echo "Input file ${var} is invalid"; exit 1
+	fi
+done
 
 # check if path is absolute, if not -- make it
 if ! [[ ${GEOM::1} == "/" ]]; then GEOM="${PWD}/${GEOM}"; fi
@@ -152,6 +155,7 @@ if [[ "${SLURM}" == "1" ]]; then
 
 		sbatch "${current_worker}"
 	done
+	tail -f "${CURRENT_LOGDIR}/stderr_*.log"
 
 else
 	# linking the laststream
